In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([ 0.14060209, -0.01740865,  0.16420626,  1.6910264 , -0.68773989,
       -0.84719893,  0.03577475,  0.79736251, -0.27199441,  0.1361455 ])

In [9]:
B = np.random.randn(10)

In [10]:
B

array([ 0.05827264,  0.76914103, -0.76134301,  0.78451177, -1.34368846,
       -0.46822823,  0.54320964, -0.92847469,  0.20928222,  1.62432288])

In [11]:
np.add(A,B)

array([ 0.19887474,  0.75173238, -0.59713675,  2.47553818, -2.03142835,
       -1.31542716,  0.57898439, -0.13111218, -0.06271219,  1.76046838])

In [12]:
np.maximum(A,B)

array([ 0.14060209,  0.76914103,  0.16420626,  1.6910264 , -0.68773989,
       -0.46822823,  0.54320964,  0.79736251,  0.20928222,  1.62432288])