In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [6]:
my_lists = [my_list1, my_list2]

In [7]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [10]:
my_array2 = np.array(my_lists)

In [11]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [12]:
my_array2.shape

(2, 4)

In [13]:
my_array2.dtype

dtype('int32')

In [14]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
my_zeros = np.zeros(5)

In [16]:
my_zeros.dtype

dtype('float64')

In [20]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [23]:
np.empty((8,4))

array([[  1.05192322e-153,   2.01537051e-047,   9.13544126e+242,
          1.43463945e-118],
       [  3.13147013e-120,   5.48282167e-096,   2.44011703e-154,
          6.01347002e-154],
       [  1.13839670e-119,   2.42766105e-154,   7.87885890e+173,
          2.74450842e-308],
       [  1.45810640e-311,   1.45810720e-311,   8.11255790e-321,
                      nan],
       [  2.24789653e+289,   0.00000000e+000,   8.79412122e+223,
          2.41182517e-109],
       [  1.81644122e+223,   6.22224394e+175,   2.34840919e+251,
          4.83245960e+276],
       [  6.01346953e-154,   1.01820564e+277,   1.27670240e+232,
          1.94901507e+227],
       [  1.67792004e+243,   5.25479985e-091,   1.77459490e+248,
          4.71592572e+257]])

In [ ]:
np.